/* Triangle numbers are generated by adding the natural numbers.
Example: the 7th triangle is: 1+2+3+4+5+6+7 = 28

Find the value of the first triangle number to have over five hundred divisors. 

Finding the number of divisors of an integer x:
x = 2^a * 3^b * 5^c * ...
num-of-div = (a+1)(b+1)(c+1)...

Therefore, to calculate the number of divisor a number has, we just need to find
all of its prime factors. */

#include <stdio.h>
#include <math.h>

int isPrime(int n)
{
    if (n%2==0 || n%3==0)
        return 0;

    for (int f = 5; f <= floor(sqrt(n)); f += 6) {
        if (n % f == 0 || n % (f+2) == 0)
            return 0;
    }

    return 1;
}

void next_prime(int *p) {
    if (*p == 2)
        *p = 3;
    else {
        do {
            *p += 2;
        } while(!isPrime(*p));
    }
}

int find_divisors(int n) {
    int i = 0;
    int p = 2;
    int div = 1;
    int factors[100] = {1};
    while (n != 1) {
        if (n % p == 0) {
            n /= p;
            factors[i]++;
        }
        else {
            if (factors[i] > 1) {
                i++;
                factors[i]++;
            }
            next_prime(&p);
        }
    }
    
    for (int j = 0; j <= i; j++) {
        div *= factors[j];
    }

    return div;
}

int main() {

    int cur = 1;
    int triangle = 1;
    int divisors;

    do {
        cur++;
        triangle += cur;
        divisors = find_divisors(triangle);
    } while(!(divisors > 500));

    printf("triangle: %d\n", triangle);
    printf("divisors: %d", divisors);

}