/* Triangle numbers are generated by adding the natural numbers.
Example: the 7th triangle is: 1+2+3+4+5+6+7 = 28

Find the value of the first triangle number to have over five hundred divisors.

Finding the number of divisors of an integer x:
x = 2^a * 3^b * 5^c * ...
num-of-div = (a+1)(b+1)(c+1)...

Therefore, to calculate the number of divisor a number has, we just need to find
all of its prime factors. */

#include <stdio.h>
#include <math.h>

#define PRIMES_QTY 1500

typedef struct {
    long int current;
    long int value;
} Triangle;

int is_prime(int n) {
    if (n%2==0 || n%3==0)
        return 0;

    for (int f = 5; f <= floor(sqrt(n)); f += 6) {
        if (n % f == 0 || n % (f+2) == 0)
            return 0;
    }

    return 1;
}

void generate_primes(int primes[PRIMES_QTY]) {
    int n = 3, isPrime;
    for (int i = 2; i < PRIMES_QTY; i++) {
        do {
            n += 2;
            isPrime = is_prime(n);
            if (isPrime)
                primes[i] = n;
        } while(!isPrime);
    }
}

int count_divisors(long int n, int primes[PRIMES_QTY]) {
    int i = 0;
    int currFactor;
    int count = 1;
    while (n != 1 && i < PRIMES_QTY) {
        currFactor = 1;
        while (n % primes[i] == 0) {
            n /= primes[i];
            currFactor++;
        }
        i++;
        count *= currFactor;
    }
    return count;
}

int main() {

    int primes[PRIMES_QTY] = {2, 3};
    Triangle triangle = {1, 1};
    int divisors;

    generate_primes(primes);

    do {
        triangle.current++;
        triangle.value += triangle.current;
        divisors = count_divisors(triangle.value, primes);
    } while(!(divisors > 500));

    printf("triangle: %ld\n", triangle.value);
    printf("divisors: %ld", divisors);

    return 0;
}
