/* Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference 
are pentagonal and D = |Pk − Pj| is minimised; what is the value of D? 

*/

#include <stdio.h>
#include <time.h>
#include <math.h>
#include <stdbool.h>

#define QTY_P 100000

int binary_search(unsigned long *p, unsigned long x, int low, int high) {
    int mid;
    while (low < high) {
        mid = (low+high)/2;
        if (x == p[mid])
            return true;
        else if (x > p[mid])
            low = mid+1;
        else
            high = mid-1;
    }
    return false;
}

int main() {

    clock_t time = clock();

    bool found = false;
    unsigned long pent[QTY_P] = {0};
    
    for (int i = 1; i <= QTY_P; i++) {
        pent[i-1] = i*(3*i-1) / 2;
    }

    for (int i = 2; i < QTY_P && !found; i++) {
        for (int j = 1; j < i && !found; j++) {
            if (binary_search(pent, pent[i]+pent[j], 0, QTY_P)
             && binary_search(pent, pent[i]-pent[j], 0, QTY_P)) 
            {
                printf("%d\n", pent[i]-pent[j]);
                found = true;
            }
        }
    }

    printf("\n\ntime elapsed: %f", (double)(clock() - time)/CLOCKS_PER_SEC);
    return 0;
}