"""
How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""

from itertools import product

sequence = set(a**b for a, b in product(range(2, 101), range(2, 101)))
print(len(sequence))