/* How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100? */

#include <stdio.h>
#include <time.h>
#include <math.h>

#define SIZE 10000

int not_in_list(long double arr[], long double n, int max) {
    for (int i = 0; i < max; i++) {
        if (arr[i] == n) {
            return 0;
        }
    }
    return 1;
}
int main() {

    clock_t time = clock();
    
    long double arr[SIZE] = {0};
    long double aux;
    int index = 0;
    for (int a = 2; a <= 100; a++) {
        for (int b = 2; b <= 100; b++) {
            aux = b*logf(a);
            if (not_in_list(arr, aux, index)) {
                arr[index] = aux;
                index++;
            }
        }
    }

    printf("number of terms: %d", index);

    time = clock() - time;
    printf("\n\ntime elapsed: %f", (double)(time)/CLOCKS_PER_SEC);
    return 0;
}
